# Generated by Django 2.1.4 on 2019-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20190504_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('task', models.TextField()),
                ('var1', models.TextField()),
                ('var2', models.TextField()),
                ('var3', models.TextField()),
                ('var4', models.TextField()),
                ('trueanswer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
