# Generated by Django 2.1.4 on 2019-05-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20190505_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('task', models.TextField()),
                ('mas', models.TextField()),
                ('trueanswer', models.TextField()),
            ],
        ),
    ]
